### ISSUE TITLE
more terminal feature

### ISSUE THREAD

**Issue by badcodebuilder** [Cveinnt/LiveTerm#12]
Will this repo support multi-line feature in future? For example:

```shell
java -Xmx1024M -Xms1024M \
    -jar minecraft_server.1.18.2.jar \
    nogui 
```
(Maybe this is a little complex, I am trying to add a command parser but failed😥)

**Comment by Cveinnt** [comment]
Thanks for the suggestion! 
I currently don't have any plan to add multi-line support as that might be a bit tricky to implement, and I am focused on other projects right now. But in case want to give it a try, feel free to submit a pull request!
