### ISSUE TITLE
Implementing an actual ls?

### ISSUE THREAD

**Issue by matmult** [Cveinnt/LiveTerm#18]
Hi, thanks for making this! Do you have any plans to implement an actual `ls` and `mkdir` function as opposed to defaulting to a hardcoded response? I want to put personal files on my website and having those would be great. For example, https://github.com/Jaredk3nt/HomeTerm

**Comment by Cveinnt** [comment]
Thanks for the suggestion - I am currently preoccupied with other projects but I do have plans to eventually implement functional `mkdir` for LiveTerm. If you'd like, feel free to make a pull request that attempts this!
