### ISSUE TITLE
Export static site?

### ISSUE THREAD

**Issue by VictorioBerra** [Cveinnt/LiveTerm#2]
Can we export a static site, and host on S3?

**Comment by Cveinnt** [comment]
Hi @VictorioBerra, thank you for your interest in LiveTerm! 
Unfortunately, LiveTerm can only be used to generate dynamic websites, as static websites are not designed to be interactive.

**Comment by VictorioBerra** [comment]
@Cveinnt Just wanted to point out, static sites can be incredibly interactive through the use of JavaScript (React, Vue, Angular), and HTML5 and CSS3.

You really only need a server-side framework if you need to interact with the file system, databases, or for added security like making protected calls to back-end APIs.

Here is a CodePen (fully static, client-side, no server, no nextjs, no vercel) that behaves very similarly to your project: https://codepen.io/jcubic/pen/BwBYOZ

**Comment by Cveinnt** [comment]
Thanks for sharing this! 

Next.js is actually a React framework geared towards production, and it is capable of [exporting static htmls](https://nextjs.org/docs/advanced-features/static-html-export) with the help of [getStaticProps()](https://nextjs.org/docs/basic-features/data-fetching/get-static-props).

I designed LiveTerm to be highly flexible and extensible, and therefore have not considered making it a static site generator. However, it is definitely possible to port LiveTerm into one.
