### ISSUE TITLE
Error 21

### ISSUE THREAD

**Issue by picarda** [Cveinnt/LiveTerm#4]
Hello,
I got this error: ERROR: [Errno 21] Is a directory: 'install'
And if I move install.sh at the root I got: ERROR: There are no scenarios; must have at least one.

Thanks

**Comment by Cveinnt** [comment]
Hi @picarda, can you specify which command you were trying to run?

**Comment by picarda** [comment]
Hi 
It’s when I do: yarn install

thanks

**Comment by Bosseur31** [comment]
Use npm for install, build and start LiveTerm.
`npm install`
`npm run dev` or `npm run build` and `npm run start`

**Comment by Cveinnt** [comment]
@picarda [Errno 21] is a python error, are you trying to run `install.sh` in a python environment? If so, could you detail the steps or the code you used to run `yarn install`?

**Comment by Bosseur31** [comment]
Hello,
For reproduce this error, i have clone git repo with this command `git clone https://github.com/Cveinnt/LiveTerm.git && cd LiveTerm` and after try to install with `yarn install && yarn dev`. But this command out `00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'install'` it's same with `yarn dev`.
I do not understand why run a shell file in python but i try and not working for me.
I have Node Js 16, python 3, ubuntu 20.04 and last yarn package install.

Install and run with npm work great for me.

Thanks for your great work.

**Comment by Bosseur31** [comment]
I'm not used to yarn. You think npm can cause problems ?

**Comment by mjh316** [comment]
I'm not familiar enough with the intricacies of either to say whether it would (though I doubt it would), I'm just commenting on why you might be facing that particular issue with yarn.

**Comment by Cveinnt** [comment]
Great discussion - thanks everyone for contributing! Closing this issue for now.
