### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by okcoder2019** [Cveinnt/LiveTerm#7]
error next@12.1.6: The engine "node" is incompatible with this module. Expected version ">=12.22.0". Got "10.19.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
This error occurs when I try to run the first step in the install process, 
sh -c "$(curl -fsSL https://raw.github.com/Cveinnt/LiveTerm/main/install/install.sh)"

**Comment by Cveinnt** [comment]
Hi, Next.js requires [Node.js](https://nodejs.org/) to be version 12.22.0 or later. Updating your Node.js install should fix this.
