### ISSUE TITLE
Can u pls help me

### ISSUE THREAD

**Issue by c1mplete** [Cveinnt/LiveTerm#9]
I am trying to do this but im on windows and i got no idea how docker works

**Comment by Cveinnt** [comment]
Hi @K0ha1 , it's not necessary to use docker if you just want to build a simple website with LiveTerm - could you specify what you were trying to do?

**Comment by c1mplete** [comment]
im just trying to make a github pages website with the terminal style u showcased in the repo

**Comment by Cveinnt** [comment]
Unfortunately LiveTerm is built as a dynamic template, and AFAIK github pages can only be used to host static pages. I would recommend using vercel/heroku/netlify to deploy your website instead - they are all free for personal use.

In any case though, Docker usage is not required - it is only intended for those who are familiar with it to facilitate deployments with Docker.
